/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.application.CartApplication;
import org.junit.Test;
import static org.junit.Assert.*;

public class CartApplicationTest {
    @Test public void appHasAGreeting() {
        CartApplication classUnderTest = new CartApplication();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
